{% set data=load_setup_py_data() %}

package:
  name: bed_annotation
  version: {{ data.version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - ngs_utils
    - numpy
  run:
    - python {{ python }}
    - ngs_utils
    - bedtools >=2.25
    - pybedtools
    - cython
    - numpy
    - gffutils
    - click
    - nose

test:
  imports:
   - bed_annotation

  commands:
   - bed_annotation --help

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
